version: "3.9"

services:
  app:
    build: .
    container_name: app
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - db
    volumes:
      - ./app:/app
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB_NAME
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  adminer:
    image: adminer:latest
    container_name: adminer
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - ${ADMINER_PORT}:${ADMINER_PORT}

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
